#!/bin/sh

device=$(uci get xunlei.config.device)
file=$(uci get xunlei.config.file)
mountpoint="`mount | grep "$device" | awk '{print $3;exit}'`"
DIR=$file/xunlei
$DIR/portal -s
sleep 1
mkdir -p ${DIR}/cfg
cd ${DIR}
FILES=$(uci get xunlei.config.xware)
url=$(uci get xunlei.config.url)

wget-ssl --quiet --no-check-certificate ${url}/${FILES}

rm -rf $DIR/portal && rm -rf $DIR/lib && unzip ${FILES}
chmod +x $DIR/* && chmod +x $DIR/lib/*
rm -rf ${FILES}
rm -rf $file/xunlei/cfg/thunder_mounts.cfg>> /dev/null 2>&1
uci set xunlei.config.up=0>> /dev/null 2>&1
uci commit 2>&1 > /dev/null
vod=$(uci get xunlei.config.vod)   
[ "$vod" -eq 1 ] && rm -f "$file"/xunlei/vod_httpserver
[ "$vod" -eq 1 ] && rm -f "$file"/xunlei/lib/vod_httpserver
sleep 3 && killall wget-ssl
