#!/bin/sh 
uci -q batch <<-EOF >/dev/null
          delete ucitrack.@xunlei[-1]
          add ucitrack xunlei
          set ucitrack.@xunlei[-1].init=xunlei
          commit ucitrack
EOF
ln -s /lib/libuClibc-1.0.*.so /lib/libdl.so.0
ln -s /lib/libuClibc-1.0.*.so /lib/libpthread.so.0
rm -f /tmp/luci-indexcahe
exit 0
